spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8889
  profiles:
    active: gitconfig

#  mongodb:
#    uri: mongodb://localhost:27017/userdb
#    database: userdb

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: leoga
#    password: leoga
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "busrefresh"
#
#server:
#  port: 8082