services:
#  mysql:
#    container_name: mysql_container
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: leoga
#      MYSQL_DATABASE: leoga
#      MYSQL_USER: leoga
#      MYSQL_PASSWORD: leoga
#      PGDATA: /data/postgres
#    volumes:
#      - mysql_data:/data/var/lib/mysql
#    ports:
#      - "3307:3306"
#    networks:
#      - mysql
#    restart: unless-stopped
#  phpmyadmin:
#    container_name: phpmyadmin_container
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: leoga
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "8484:80"
#    networks:
#      - mysql
#    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:18
    environment:
      POSTGRES_USER: leoga
      POSTGRES_PASSWORD: leoga
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postdres
    ports:
      - "5432:5432"
    networks:
    - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
    - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  postgres:
    driver: bridge
#  mysql:
#    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq_data:
#  mysql_data: