services:
#  mysql:
#    container_name: mysql_container
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: leoga
#      MYSQL_DATABASE: leoga
#      MYSQL_USER: leoga
#      MYSQL_PASSWORD: leoga
#      PGDATA: /data/postgres
#    volumes:
#      - mysql_data:/data/var/lib/mysql
#    ports:
#      - "3307:3306"
#    networks:
#      - mysql
#    restart: unless-stopped
#  phpmyadmin:
#    container_name: phpmyadmin_container
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: leoga
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "8484:80"
#    networks:
#      - mysql
#    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:18
    environment:
      POSTGRES_USER: leoga
      POSTGRES_PASSWORD: leoga
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
    - backend
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
    - backend
    restart: unless-stopped
  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
  kafka:
    container_name: kafka_container
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - kafka:/var/lib/kafka/data
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.5.6
    command: start-dev
    ports:
      - "8443:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - keycloak-data:/opt/keycloak/data
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mongo:/data/db


networks:
  backend:
    driver: bridge
#  mysql:
#    driver: bridge

volumes:
  postgres:
  pgadmin:
  kafka:
  keycloak-data:
  mongo:
#  mysql_data: