spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8889
  profiles:
    active: gitconfig

#  datasource:
#    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:postgresql://ep-winter-sound-aghzeeyb-pooler.c-2.eu-central-1.aws.neon.tech/product?sslmode=require&channel_binding=require
#    url: jdbc:mysql://localhost:3307/leoga
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        format_sql: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "busrefresh"
#
#server:
#  port: 8081