spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:postgresql://ep-winter-sound-aghzeeyb-pooler.c-2.eu-central-1.aws.neon.tech/product?sslmode=require&channel_binding=require
#    url: jdbc:mysql://localhost:3307/leoga
    username: leoga
    password: leoga
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081