apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: product
  namespaceSelector:
    matchNames:
      - ecomapp
  targetLabels:
    - application
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 3s